### ISSUE TITLE
Change Bluetooth device name

### ISSUE THREAD

**Issue by haithembelhaj** [calliope-edu/scratch-gui#1]
The device broadcasts the name "BBC mico:bit" over bluetooth
This should be changed to "Calliope mini"

_Note_
It seems the string comes from this project https://github.com/lancaster-university/codal-microbit-v2/blob/9a03c691c12474852819843f21e32908ab405a2f/source/bluetooth/MicroBitBLEManager.cpp#L113

**Comment by haithembelhaj** [comment]
@joernalraun there seems to be no direct way to change the name as this Hex compiler uses `pxt` https://github.com/calliope-edu/pxt-Scratch-more/blob/master/pxt.json which then references this project https://github.com/yokobond/microbit/blob/mbit-more/README.md


Do you maybe already have a working Hex runtime with another Bluetooth device name for Calliope mini?

**Comment by joernalraun** [comment]
Yes! If you compile it within this link it should be advertised as "Calliope mini [XXXXX]":
https://makecode.calliope.cc/_iEeLiTPAxJJk

**Comment by joernalraun** [comment]
@Amerlander tbd

**Comment by joernalraun** [comment]
https://github.com/calliope-edu/scratch-link

**Comment by joernalraun** [comment]
@haithembelhaj funktioniert nun, allerdings sollte der Gerätename [xxxxx] auch im Dialog stehen, weil man ansonsten bei mehreren Geräten nicht weiß, mit wem man sich verbinden soll.

**Comment by haithembelhaj** [comment]
@joernalraun Es sieht richtig aus für mich. Ich sehe Gerätename [xxxxx] 

![Screenshot from 2024-04-30 11-44-48](https://github.com/calliope-edu/scratch-gui/assets/1311570/cfda4926-3ad0-4635-868c-aa9ef6352f2b)

**Comment by joernalraun** [comment]
Ich meinte das Fenster:
Da stand (im Kasten mit 1/2) auch der Name. Mobil bekommt man da wohl auch das Gerät mit Namen angezeigt, ich glaube aber, dass der jetzt auch wieder drin ist). teste ich gleich nochmal.
<img width="519" alt="Bildschirmfoto 2024-04-30 um 12 08 03" src="https://github.com/calliope-edu/scratch-gui/assets/14014852/b530e37a-47d3-4cce-bb73-791b74c407c4">

**Comment by joernalraun** [comment]
@haithembelhaj funktioniert!
