### ISSUE TITLE
Change main extension Icon on left, bottom side

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/scratch-gui#10]
![IconBlocks](https://github.com/calliope-edu/scratch-gui/assets/14014852/0244fe1d-309c-44ff-bf9c-9f7678eb756c)

<img width="64" alt="Bildschirmfoto 2024-04-15 um 16 26 41" src="https://github.com/calliope-edu/scratch-gui/assets/14014852/cf84fbc8-e3ea-4815-9721-5f7c640e6400">

@haithembelhaj

**Comment by haithembelhaj** [comment]
@joernalraun change was deployed. Please check it out!

**Comment by joernalraun** [comment]
Super, leider ist das in der Größe recht schwer zu erkennen. Ich füge ein Update hinzu...

**Comment by joernalraun** [comment]
![322518240-0244fe1d-309c-44ff-bf9c-9f7678eb756c](https://github.com/calliope-edu/scratch-gui/assets/14014852/0c16ec58-eb33-44e9-8693-e91de929d1c2)
@haithembelhaj

**Comment by joernalraun** [comment]
Original Post: https://github.com/calliope-edu/scratch-gui/issues/9

**Comment by haithembelhaj** [comment]
@joernalraun I changed the icon on the left. Please review!
