### ISSUE TITLE
Pin Blöcke Liste anpassen

### ISSUE THREAD

**Issue by fabianhugo** [calliope-edu/scratch-gui#13]
Bei den Blöcken:
- "Setze Eingang P0 auf Pulldown " 
-  "Pin P0 hoch?",
- "setze digitalen Ausgang P0 auf 0"
- "setze analogen Ausgang P0 auf 0%"
- setze Servo an P0 auf Winkel 0°"
- warte auf nichts an Pin P0
- Wenn ein Impuls tief an Pin P0
- Wert von Impuls tief an Pin P0
ist die Liste glaube ich noch nicht angepasst. Screenshot:
![grafik](https://github.com/calliope-edu/scratch-gui/assets/32654742/ebb42fb6-de0a-49e6-b9e1-6abe1f0be567)
Im besten Falle wäre jeweils die Liste: 
P0, P1, P2, P3, C8, C12, C13, C14, C15, C16, C17. Also aus P ein C machen ab C8 sowie P3 und C17 hinzufügen.
Ich denke, dass muss insgesamt nur einmal für alle Blöcke gemacht werden.

**Comment by joernalraun** [comment]
@haithembelhaj ?

**Comment by haithembelhaj** [comment]
@joernalraun @fabianhugo @Amerlander die vorhandenen Pins umzubenennen ist kein Ding. (siehe aktualisierte GUI version)

Pins hinzuzufügen ist aber wieder von der Hex abhängig denke ich.Die Stelle muss angepasst werden https://github.com/calliope-edu/pxt-Scratch-more/blob/master/MbitMoreDevice.h#L148C3-L148C53 

@Amerlander kannst du bitte P3 und C17 (GPIO 3 und 17) hinzufügen und mir die neue Hex zukommen lassen bitte?

PS: noch eine Sache kannst du mir auch die MakeCode pxt.json Datei, die du für die Herstellung der Hex benutzt hast, zukommen lassen. Ich glaube ich hätte eine Idee womit wir Releases automatisch herstellen könnten :)

**Comment by Amerlander** [comment]
Die Extension kann man nicht direkt in MakeCode laden, weil es eine alter Version braucht, die gar nicht online ist.

Die Version ist hier: https://github.com/calliope-edu/pxt-calliope/tree/V5.0.12-SCRATCH

MakeCode dann lokal starten mit:
- git clonen, branch "V5.0.12-SCRATCH"
- npm install -g pxt
- npm install
- pxt serve
- PXT öffnet sich, neues Projekt & dort noch den More-Start Block platzieren.

Die Erweiterung liegt im Ordner /libs/scratch und kann da angepasst werden, wobei ich gerade die Änderungen auch im repo der Erweiterung habe (sind also bis auf die dependencies Verlinkung in der pxt.json identisch)
