### ISSUE TITLE
Add color Block

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/scratch-gui#14]
When adding RGB-LED color we might need to do a little trick by using the label block.
<img width="640" alt="Bildschirmfoto 2024-04-25 um 11 08 43" src="https://github.com/calliope-edu/scratch-gui/assets/14014852/49d5d580-b274-419f-8a65-57ba58118d9c">
This way we get 11 characters/numbers send to the calliope mini.
When using the label block there...
![microbit-Screenshot](https://github.com/calliope-edu/scratch-gui/assets/14014852/142f4fd0-6676-4680-b6bd-52a4b4f921ad)
we should be able to read the data (the program currently shows the value, we will need to build the values there and put them into the colors block).

Within Scratch the block should work like this:
![Bildschirmfoto 2024-04-25 um 11 16 50](https://github.com/calliope-edu/scratch-gui/assets/14014852/c1a3a027-eff6-47e9-bd75-90a72f9d701f)

But should look like this:
![Color-2024-04-25-um-11 16 34](https://github.com/calliope-edu/scratch-gui/assets/14014852/30ad6ef2-3811-4a8d-be76-f7f8bde7c79e)
The Text should be "setze Farben auf" as in MakeCode...
The value must be generated to this XXXgXXXbXXX (no r, because the string can't be longer...) – we would only need RGB values, if it is easier to change the picker to that, please do so...
Does this makes sense to you @haithembelhaj ?

**Comment by joernalraun** [comment]
This should be close to the final program: https://makecode.calliope.cc/_MjCaAJ6PaRuP this works now, though it might need some refinement... ;) @haithembelhaj
@Amerlander can you have a look at it and build a correct Hex file?

**Comment by joernalraun** [comment]
If this would work, we could also add more labels to control each of the three RGB-LEDs independently... ;)

**Comment by Amerlander** [comment]
@joernalraun @haithembelhaj shouldn't we add a function to MBitMoreDevice.cpp which controlls the rgb led like its done for the servo ( https://github.com/calliope-edu/pxt-Scratch-more/blob/5feadf61396f9818319223ed8eaca210ad83243b/MbitMoreDevice.cpp#L928 )?

I would also prefer to seperate the colors by comma, so we can just split the string. That would work for cases like "123,10,1". 

![image](https://github.com/calliope-edu/scratch-gui/assets/3764089/e11832b5-6a00-495e-814e-16b2fe4ca3cf)
https://makecode.calliope.cc/_eL0MFqUrE6VM

**Comment by Amerlander** [comment]
The "set LED" function is not downgraded into the MakeCode V5, so I would have to do this first. Also we can not use "#IF CODAL" in ts files, so we also would have to diasable the universal hex file first. I think the better approach will be to solve this inside the cpp file, so we can handle DAL and CODAL and do not have to change MakeCode that much.

**Comment by joernalraun** [comment]
Ok, I thought this might be the quickest way to go, but you should be correct! Sorry, @haithembelhaj and @Amerlander for the confusion...

**Comment by haithembelhaj** [comment]
@joernalraun @Amerlander please give me the final specs when you are ready I will try to add the block GUI first :)

**Comment by haithembelhaj** [comment]
@joernalraun @Amerlander I added a dummy RGB block 
![image](https://github.com/calliope-edu/scratch-gui/assets/1311570/afc6bab3-1caf-4ce6-8c2b-bd72face33c6)
English: "set RGB-LEDs to"
With this block I could send a custom command to the board with the color info. Please send me the specs as soon as you have them :)

**Comment by joernalraun** [comment]
Another image with both color blocks (the picker should be made so that it is easy to implement) ![Farben](https://github.com/calliope-edu/scratch-gui/assets/14014852/8496d359-a66e-486c-84a0-fa538765eed1)

**Comment by joernalraun** [comment]
Unfortunately we also need a block with the name: "turn off RGB-LEDs"/"eingebaute RGB-LEDs ausschalten" that only sends three black LED colors...

**Comment by Amerlander** [comment]
@haithembelhaj here is our implementation for the RGB LED.

The function receives a uint8_t array.
 When the first item is `0x05` the items 1-3 are used as rgb for the first led. 4-6 for the second and 7-9 for the third.

```
MbitMoreCommand::CMD_RGB === 0x05
```

Youll find the code of the implementation in this git diff:
https://github.com/calliope-edu/pxt-calliope/commit/24f555d1f2450badc2692c553633505282f8c2cb#diff-c4800e584df825723bdd7802e624a8f03965058c9be0a3f9883288bd519641a1

The HEX file is attached here:
[microbit-Calliope-More-RGB-LED.zip](https://github.com/calliope-edu/scratch-gui/files/15148535/microbit-Calliope-More-RGB-LED.zip)

**Comment by haithembelhaj** [comment]
@joernalraun @Amerlander Ohh my I didn't see there were 3 RGB leds. 

I added the extra color pickers and connected them with the command. Somehow I had to send [G, R, B] (instead of [R, G, B] to make the color work properly. Maybe I'm missing something https://github.com/xcratch/scratch-vm/commit/106b570969f62c262a203f159ec39bdfccfd5901

Please test it!

**Comment by Amerlander** [comment]
@haithembelhaj oh, the GRB instead of RGB is somewhere in the Neopixel... it has to be switched somewhere, I think your function `colorHexToRGB ` is a good place. Otherwise we would just have a switched array index, which might be even more confusing.

**Comment by Amerlander** [comment]
Wait, the Calliope 2 need RGB, Calliope 3 GRB. So I think I'll update this in the hexfile. So you can change your code to really send RGB and I'll provide a new hex file instead.

**Comment by Amerlander** [comment]
@haithembelhaj I made a new HEX file with switched Red and Green. So you dont have to switch them in the Editor.

https://github.com/calliope-edu/pxt-calliope/commit/9f08981895953c8fd9a6a9ee388376b6dcea03fd

[microbit-Calliope-More-RGB-LED.zip](https://github.com/calliope-edu/scratch-gui/files/15150449/microbit-Calliope-More-RGB-LED.zip)

**Comment by joernalraun** [comment]
@haithembelhaj runs well now! 🤖
Can you rename the strings to "set RGB-LEDs to"/"setze Farben auf" or link me to the included file?

**Comment by haithembelhaj** [comment]
@joernalraun @Amerlander I switch back to RGB and chaged the strings :)

FYI the strings are here https://github.com/calliope-edu/scratch-vm/blob/calliope/src/extensions/calliopeMini/translations.json
