### ISSUE TITLE
Label-Blocks to be hidden

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/scratch-gui#15]
We are going to use the functionality for these blocks, but they are not longer being usable by students, as they can't access them freely in MakeCode. Therefore they should be hidden... <img width="559" alt="Bildschirmfoto 2024-04-29 um 13 15 54" src="https://github.com/calliope-edu/scratch-gui/assets/14014852/64908c31-eaea-4f87-98c6-7504efb62f2a">

These have simply no real function and should be also hidden:
<img width="312" alt="Bildschirmfoto 2024-04-29 um 13 18 37" src="https://github.com/calliope-edu/scratch-gui/assets/14014852/6fd3770f-a1c5-45fc-9045-47e5585f68e0">
@haithembelhaj

**Comment by haithembelhaj** [comment]
@joernalraun done! Please review!
