### ISSUE TITLE
Help Button Link

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/scratch-gui#18]
Help button links should go to: https://calliope.cc/programmieren/editoren/calliope-mini-blocks-scratch-programmieren

<img width="501" alt="Bildschirmfoto 2024-04-30 um 10 35 31" src="https://github.com/calliope-edu/scratch-gui/assets/14014852/204e119c-de4a-4ea6-ba04-9afb7b495512">

**Comment by haithembelhaj** [comment]
Done! Deploying!
