### ISSUE TITLE
No link on main icon

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/scratch-gui#19]
@haithembelhaj The link on the icon could make some problems when using the iOS app. Please just delete it if possible or change to https://blocks.calliope.cc (start page).
<img width="64" alt="Bildschirmfoto 2024-05-02 um 12 54 30" src="https://github.com/calliope-edu/scratch-gui/assets/14014852/1ca9dddd-4e87-4bfc-a0c2-a7a0bb989c78">

**Comment by haithembelhaj** [comment]
@joernalraun I removed the click from the logo
