### ISSUE TITLE
Change Name, show without number

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/scratch-gui#7]
Show only name in Headline, no Versionnumber
<img width="526" alt="Bildschirmfoto 2024-04-15 um 16 22 29" src="https://github.com/calliope-edu/scratch-gui/assets/14014852/231a17cb-6357-448a-a28d-b2acabeb6d77">
@haithembelhaj

**Comment by haithembelhaj** [comment]
@joernalraun change was deployed. Please check it out!
