### ISSUE TITLE
Change Icon on Calliope mini blocks

### ISSUE THREAD

**Issue by joernalraun** [calliope-edu/scratch-gui#9]
Change the icon from screenshot to the attached SVG.

<img width="243" alt="Bildschirmfoto 2024-04-15 um 16 23 48" src="https://github.com/calliope-edu/scratch-gui/assets/14014852/970e39d4-5a7a-4c72-b2fd-db6bcad7fcfe">
![Icon_Blocks](https://github.com/calliope-edu/scratch-gui/assets/14014852/041e2aa5-28c3-4929-b0d2-d8fbef0a4367)

**Comment by joernalraun** [comment]
![Icon_Blocks](https://github.com/calliope-edu/scratch-gui/assets/14014852/8dac44b6-4d93-40ef-b629-63e8ccb017cb)
@haithembelhaj

**Comment by joernalraun** [comment]
The above one is an SVG, here is the PNG.
![Icon](https://github.com/calliope-edu/scratch-gui/assets/14014852/7c9d2fcc-408a-4b08-895b-d243bb418f61)

**Comment by haithembelhaj** [comment]
@joernalraun change was deployed. Please check it out!

**Comment by joernalraun** [comment]
Könntest du das Icon oben links wechseln? @haithembelhaj 
![221d361feda571484db66eef8496721b](https://github.com/calliope-edu/scratch-gui/assets/14014852/f505c863-a93d-45df-8623-90eceedef25c)
![Bildschirmfoto 2024-04-24 um 12 34 31](https://github.com/calliope-edu/scratch-gui/assets/14014852/74f555cb-8e7c-4189-9bb2-bc4286949043)

**Comment by haithembelhaj** [comment]
@joernalraun I changed the header menu icon! Please review
